# Generated by Django 5.2.14 on 2026-05-24 06:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Deporte',
                'verbose_name_plural': 'Deportes',
                'db_table': 'eventos_deporte',
                'ordering': ['nombre'],
                'indexes': [models.Index(fields=['nombre'], name='eventos_dep_nombre_7c97ad_idx'), models.Index(fields=['activo'], name='eventos_dep_activo_768b85_idx')],
            },
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('abreviatura', models.CharField(blank=True, max_length=10, null=True)),
                ('pais', models.CharField(blank=True, max_length=80, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('deporte', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipos', to='eventos.deporte')),
            ],
            options={
                'verbose_name': 'Equipo',
                'verbose_name_plural': 'Equipos',
                'db_table': 'eventos_equipo',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre visible del evento. Ejemplo: Perú vs Argentina.', max_length=180)),
                ('estado', models.CharField(choices=[('programado', 'Programado'), ('en_vivo', 'En vivo'), ('finalizado', 'Finalizado'), ('suspendido', 'Suspendido'), ('anulado', 'Anulado')], default='programado', max_length=20)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('marcador_local', models.PositiveIntegerField(blank=True, null=True)),
                ('marcador_visitante', models.PositiveIntegerField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('deporte', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eventos', to='eventos.deporte')),
                ('equipo_local', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eventos_como_local', to='eventos.equipo')),
                ('equipo_visitante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eventos_como_visitante', to='eventos.equipo')),
            ],
            options={
                'verbose_name': 'Evento deportivo',
                'verbose_name_plural': 'Eventos deportivos',
                'db_table': 'eventos_evento',
                'ordering': ['fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='ResultadoEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marcador_local', models.PositiveIntegerField()),
                ('marcador_visitante', models.PositiveIntegerField()),
                ('resultado_1x2', models.CharField(choices=[('local', 'Gana local'), ('empate', 'Empate'), ('visitante', 'Gana visitante')], max_length=20)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('evento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resultado', to='eventos.evento')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resultados_registrados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Resultado de evento',
                'verbose_name_plural': 'Resultados de eventos',
                'db_table': 'eventos_resultado',
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.AddIndex(
            model_name='equipo',
            index=models.Index(fields=['nombre'], name='eventos_equ_nombre_47ee47_idx'),
        ),
        migrations.AddIndex(
            model_name='equipo',
            index=models.Index(fields=['deporte'], name='eventos_equ_deporte_f0a092_idx'),
        ),
        migrations.AddIndex(
            model_name='equipo',
            index=models.Index(fields=['activo'], name='eventos_equ_activo_ea2399_idx'),
        ),
        migrations.AddConstraint(
            model_name='equipo',
            constraint=models.UniqueConstraint(fields=('nombre', 'deporte'), name='unique_equipo_por_deporte'),
        ),
        migrations.AddIndex(
            model_name='evento',
            index=models.Index(fields=['estado'], name='eventos_eve_estado_6b5412_idx'),
        ),
        migrations.AddIndex(
            model_name='evento',
            index=models.Index(fields=['fecha_inicio'], name='eventos_eve_fecha_i_0df3d8_idx'),
        ),
        migrations.AddIndex(
            model_name='evento',
            index=models.Index(fields=['deporte'], name='eventos_eve_deporte_38b09b_idx'),
        ),
        migrations.AddIndex(
            model_name='evento',
            index=models.Index(fields=['activo'], name='eventos_eve_activo_8e8c71_idx'),
        ),
        migrations.AddConstraint(
            model_name='evento',
            constraint=models.CheckConstraint(condition=models.Q(('equipo_local', models.F('equipo_visitante')), _negated=True), name='evento_equipos_diferentes'),
        ),
        migrations.AddIndex(
            model_name='resultadoevento',
            index=models.Index(fields=['resultado_1x2'], name='eventos_res_resulta_70b08c_idx'),
        ),
        migrations.AddIndex(
            model_name='resultadoevento',
            index=models.Index(fields=['fecha_registro'], name='eventos_res_fecha_r_982b11_idx'),
        ),
    ]
