# Generated by Django 5.2.14 on 2026-05-27 21:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Liga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, unique=True)),
                ('pais', models.CharField(blank=True, default='', max_length=80)),
                ('activa', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('deporte', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ligas', to='eventos.deporte')),
            ],
            options={
                'verbose_name': 'Liga',
                'verbose_name_plural': 'Ligas',
                'db_table': 'eventos_liga',
                'ordering': ['deporte__nombre', 'nombre'],
            },
        ),
        migrations.AddField(
            model_name='evento',
            name='liga',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos', to='eventos.liga'),
        ),
        migrations.AddIndex(
            model_name='liga',
            index=models.Index(fields=['deporte'], name='eventos_lig_deporte_e5d9a2_idx'),
        ),
        migrations.AddIndex(
            model_name='liga',
            index=models.Index(fields=['activa'], name='eventos_lig_activa_8106ff_idx'),
        ),
    ]
