# Generated by Django 5.2.14 on 2026-05-24 06:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mercados', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Odd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=4, help_text='Cuota decimal europea. Ejemplo: 2.5000', max_digits=18)),
                ('margen_operador', models.DecimalField(decimal_places=4, default=0, help_text='Margen aplicado por el operador.', max_digits=18)),
                ('activa', models.BooleanField(default=True)),
                ('suspendida', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('actualizada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cuotas_actualizadas', to=settings.AUTH_USER_MODEL)),
                ('seleccion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='odd', to='mercados.seleccionmercado')),
            ],
            options={
                'verbose_name': 'Cuota',
                'verbose_name_plural': 'Cuotas',
                'db_table': 'cuotas_odd',
                'ordering': ['seleccion'],
            },
        ),
        migrations.CreateModel(
            name='OddHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_anterior', models.DecimalField(decimal_places=4, max_digits=18)),
                ('valor_nuevo', models.DecimalField(decimal_places=4, max_digits=18)),
                ('margen_operador', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('motivo', models.CharField(blank=True, max_length=180, null=True)),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True)),
                ('cambiado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historial_cuotas_cambiadas', to=settings.AUTH_USER_MODEL)),
                ('odd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='cuotas.odd')),
            ],
            options={
                'verbose_name': 'Historial de cuota',
                'verbose_name_plural': 'Historial de cuotas',
                'db_table': 'cuotas_odd_history',
                'ordering': ['-fecha_cambio'],
            },
        ),
        migrations.AddIndex(
            model_name='odd',
            index=models.Index(fields=['activa'], name='cuotas_odd_activa_83ee19_idx'),
        ),
        migrations.AddIndex(
            model_name='odd',
            index=models.Index(fields=['suspendida'], name='cuotas_odd_suspend_0e1c20_idx'),
        ),
        migrations.AddIndex(
            model_name='odd',
            index=models.Index(fields=['fecha_actualizacion'], name='cuotas_odd_fecha_a_7339a5_idx'),
        ),
        migrations.AddConstraint(
            model_name='odd',
            constraint=models.CheckConstraint(condition=models.Q(('valor__gt', 1)), name='odd_valor_mayor_que_uno'),
        ),
        migrations.AddConstraint(
            model_name='odd',
            constraint=models.CheckConstraint(condition=models.Q(('margen_operador__gte', 0)), name='odd_margen_operador_no_negativo'),
        ),
        migrations.AddIndex(
            model_name='oddhistory',
            index=models.Index(fields=['odd'], name='cuotas_odd__odd_id_d47101_idx'),
        ),
        migrations.AddIndex(
            model_name='oddhistory',
            index=models.Index(fields=['fecha_cambio'], name='cuotas_odd__fecha_c_8e32d2_idx'),
        ),
        migrations.AddConstraint(
            model_name='oddhistory',
            constraint=models.CheckConstraint(condition=models.Q(('valor_anterior__gt', 1)), name='odd_history_valor_anterior_mayor_que_uno'),
        ),
        migrations.AddConstraint(
            model_name='oddhistory',
            constraint=models.CheckConstraint(condition=models.Q(('valor_nuevo__gt', 1)), name='odd_history_valor_nuevo_mayor_que_uno'),
        ),
    ]
