# Generated by Django 5.2.14 on 2026-05-26 06:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditIntegrityCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('es_valida', models.BooleanField(default=True)),
                ('total_registros', models.PositiveIntegerField(default=0)),
                ('errores_detectados', models.JSONField(blank=True, help_text='Lista de errores encontrados durante la verificación.', null=True)),
                ('fecha_ejecucion', models.DateTimeField(auto_now_add=True)),
                ('ejecutado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verificaciones_auditoria', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Verificación de integridad',
                'verbose_name_plural': 'Verificaciones de integridad',
                'db_table': 'auditoria_integrity_check',
                'ordering': ['-fecha_ejecucion'],
                'indexes': [models.Index(fields=['es_valida'], name='auditoria_i_es_vali_330a4e_idx'), models.Index(fields=['fecha_ejecucion'], name='auditoria_i_fecha_e_4314b5_idx')],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_evento', models.CharField(choices=[('wallet_movement', 'Movimiento de wallet'), ('bet_created', 'Apuesta creada'), ('bet_settled', 'Apuesta liquidada'), ('odd_changed', 'Cambio de cuota'), ('user_kyc', 'Cambio KYC'), ('responsible_gaming', 'Juego responsable'), ('fraud_alert', 'Alerta antifraude'), ('system', 'Sistema')], max_length=40)),
                ('entidad', models.CharField(help_text='Nombre de la entidad auditada. Ejemplo: Bet, LedgerTransaction, Odd.', max_length=80)),
                ('entidad_id', models.CharField(help_text='ID de la entidad auditada.', max_length=80)),
                ('accion', models.CharField(help_text='Acción realizada. Ejemplo: created, updated, settled, blocked.', max_length=80)),
                ('payload', models.JSONField(help_text='Datos relevantes del evento auditado.')),
                ('previous_hash', models.CharField(blank=True, help_text='Hash del registro anterior.', max_length=64, null=True)),
                ('current_hash', models.CharField(help_text='Hash calculado del registro actual.', max_length=64, unique=True)),
                ('ip_origen', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditorias_creadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de auditoría',
                'verbose_name_plural': 'Registros de auditoría',
                'db_table': 'auditoria_audit_log',
                'ordering': ['-fecha_creacion'],
                'indexes': [models.Index(fields=['tipo_evento'], name='auditoria_a_tipo_ev_0255c7_idx'), models.Index(fields=['entidad'], name='auditoria_a_entidad_9d69ce_idx'), models.Index(fields=['entidad_id'], name='auditoria_a_entidad_e57311_idx'), models.Index(fields=['accion'], name='auditoria_a_accion_c59498_idx'), models.Index(fields=['fecha_creacion'], name='auditoria_a_fecha_c_7f49f5_idx'), models.Index(fields=['current_hash'], name='auditoria_a_current_06a86e_idx')],
            },
        ),
    ]
