# Generated by Django 5.2.14 on 2026-05-27 21:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apuestas_core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FraudAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_alerta', models.CharField(choices=[('apuesta_alta', 'Apuesta de monto alto'), ('muchas_apuestas_rapidas', 'Muchas apuestas rápidas'), ('apuestas_repetidas_evento', 'Apuestas repetidas en mismo evento')], max_length=40)),
                ('severidad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta')], default='baja', max_length=10)),
                ('descripcion', models.TextField()),
                ('estado', models.CharField(choices=[('abierta', 'Abierta'), ('revisada', 'Revisada'), ('descartada', 'Descartada')], default='abierta', max_length=15)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('bet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertas_fraude', to='apuestas_core.bet')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas_fraude', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Alerta de fraude',
                'verbose_name_plural': 'Alertas de fraude',
                'db_table': 'antifraude_fraud_alert',
                'ordering': ['-fecha_creacion'],
                'indexes': [models.Index(fields=['usuario'], name='antifraude__usuario_a26d1a_idx'), models.Index(fields=['tipo_alerta'], name='antifraude__tipo_al_22ce9a_idx'), models.Index(fields=['severidad'], name='antifraude__severid_1a882b_idx'), models.Index(fields=['estado'], name='antifraude__estado_a7fdb3_idx'), models.Index(fields=['fecha_creacion'], name='antifraude__fecha_c_2ac31d_idx')],
            },
        ),
    ]
