# Generated by Django 5.2.14 on 2026-05-24 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mercado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('1x2', '1X2'), ('over_under', 'Over/Under'), ('btts', 'Ambos equipos anotan'), ('handicap', 'Handicap')], default='1x2', max_length=30)),
                ('nombre', models.CharField(help_text='Ejemplo: Resultado final 1X2', max_length=120)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('suspendido', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mercados', to='eventos.evento')),
            ],
            options={
                'verbose_name': 'Mercado',
                'verbose_name_plural': 'Mercados',
                'db_table': 'mercados_mercado',
                'ordering': ['evento', 'tipo'],
            },
        ),
        migrations.CreateModel(
            name='SeleccionMercado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('local', 'Gana local'), ('empate', 'Empate'), ('visitante', 'Gana visitante'), ('over_25', 'Más de 2.5 goles'), ('under_25', 'Menos de 2.5 goles'), ('ambos_si', 'Ambos anotan'), ('ambos_no', 'Ambos no anotan')], max_length=30)),
                ('nombre', models.CharField(help_text='Ejemplo: Gana local, Empate, Gana visitante', max_length=120)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('mercado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selecciones', to='mercados.mercado')),
            ],
            options={
                'verbose_name': 'Selección de mercado',
                'verbose_name_plural': 'Selecciones de mercado',
                'db_table': 'mercados_seleccion',
                'ordering': ['mercado', 'tipo'],
            },
        ),
        migrations.AddIndex(
            model_name='mercado',
            index=models.Index(fields=['evento'], name='mercados_me_evento__25486f_idx'),
        ),
        migrations.AddIndex(
            model_name='mercado',
            index=models.Index(fields=['tipo'], name='mercados_me_tipo_10203b_idx'),
        ),
        migrations.AddIndex(
            model_name='mercado',
            index=models.Index(fields=['activo'], name='mercados_me_activo_956257_idx'),
        ),
        migrations.AddIndex(
            model_name='mercado',
            index=models.Index(fields=['suspendido'], name='mercados_me_suspend_decf34_idx'),
        ),
        migrations.AddConstraint(
            model_name='mercado',
            constraint=models.UniqueConstraint(fields=('evento', 'tipo'), name='unique_mercado_tipo_por_evento'),
        ),
        migrations.AddIndex(
            model_name='seleccionmercado',
            index=models.Index(fields=['mercado'], name='mercados_se_mercado_a10236_idx'),
        ),
        migrations.AddIndex(
            model_name='seleccionmercado',
            index=models.Index(fields=['tipo'], name='mercados_se_tipo_2244fc_idx'),
        ),
        migrations.AddIndex(
            model_name='seleccionmercado',
            index=models.Index(fields=['activo'], name='mercados_se_activo_bf2473_idx'),
        ),
        migrations.AddConstraint(
            model_name='seleccionmercado',
            constraint=models.UniqueConstraint(fields=('mercado', 'tipo'), name='unique_seleccion_tipo_por_mercado'),
        ),
    ]
