# Generated by Django 5.2.14 on 2026-05-28 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercados', '0002_default_football_markets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mercado',
            name='tipo',
            field=models.CharField(choices=[('1x2', '1X2'), ('over_under_05', 'Mas/Menos 0.5 goles'), ('over_under_15', 'Mas/Menos 1.5 goles'), ('over_under_25', 'Mas/Menos 2.5 goles'), ('over_under_35', 'Mas/Menos 3.5 goles'), ('over_under', 'Over/Under'), ('btts', 'Ambos equipos anotan'), ('double_chance', 'Doble oportunidad'), ('draw_no_bet', 'Apuesta sin empate'), ('exact_goals', 'Cantidad exacta de goles'), ('handicap', 'Handicap')], default='1x2', max_length=30),
        ),
        migrations.AlterField(
            model_name='seleccionmercado',
            name='tipo',
            field=models.CharField(choices=[('local', 'Gana local'), ('empate', 'Empate'), ('visitante', 'Gana visitante'), ('local_empate', 'Local o empate'), ('local_visitante', 'Local o visitante'), ('empate_visitante', 'Empate o visitante'), ('over_05', 'Mas de 0.5 goles'), ('under_05', 'Menos de 0.5 goles'), ('over_15', 'Mas de 1.5 goles'), ('under_15', 'Menos de 1.5 goles'), ('over_25', 'Más de 2.5 goles'), ('under_25', 'Menos de 2.5 goles'), ('over_35', 'Mas de 3.5 goles'), ('under_35', 'Menos de 3.5 goles'), ('ambos_si', 'Ambos anotan'), ('ambos_no', 'Ambos no anotan'), ('exact_0', '0 goles'), ('exact_1', '1 gol'), ('exact_2', '2 goles'), ('exact_3', '3 goles'), ('exact_4_plus', '4+ goles')], max_length=30),
        ),
    ]
