# Generated by Django 5.2.14 on 2026-05-24 05:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(help_text='DNI peruano de 8 dígitos.', max_length=8, unique=True)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('estado_cuenta', models.CharField(choices=[('pendiente_verificacion', 'Pendiente de verificación'), ('verificado', 'Verificado'), ('bloqueado', 'Bloqueado'), ('autoexcluido', 'Autoexcluido')], default='pendiente_verificacion', max_length=30)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_apuestas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de usuario',
                'verbose_name_plural': 'Perfiles de usuarios',
                'db_table': 'usuarios_perfil',
                'ordering': ['apellidos', 'nombres'],
            },
        ),
        migrations.CreateModel(
            name='VerificacionKYC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni_verificado', models.BooleanField(default=False)),
                ('mayor_edad_verificado', models.BooleanField(default=False)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('fecha_verificacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('perfil', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kyc', to='usuarios.perfilusuario')),
                ('verificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kyc_verificados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Verificación KYC',
                'verbose_name_plural': 'Verificaciones KYC',
                'db_table': 'usuarios_kyc',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.AddIndex(
            model_name='perfilusuario',
            index=models.Index(fields=['dni'], name='usuarios_pe_dni_75debc_idx'),
        ),
        migrations.AddIndex(
            model_name='perfilusuario',
            index=models.Index(fields=['estado_cuenta'], name='usuarios_pe_estado__7cf0b1_idx'),
        ),
        migrations.AddIndex(
            model_name='verificacionkyc',
            index=models.Index(fields=['dni_verificado'], name='usuarios_ky_dni_ver_1be3c2_idx'),
        ),
        migrations.AddIndex(
            model_name='verificacionkyc',
            index=models.Index(fields=['mayor_edad_verificado'], name='usuarios_ky_mayor_e_e7911e_idx'),
        ),
    ]
