# Generated by Django 5.2.14 on 2026-05-27 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='dni',
            field=models.CharField(help_text='Número de documento (DNI 8 dígitos, CE/Pasaporte hasta 12).', max_length=12, unique=True),
        ),
    ]
