# Generated by Django 6.0.4 on 2026-05-28 20:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_perfil_dni_max_length_12'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoSesionUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sesion_activa', models.BooleanField(default=False, help_text='Indica si el usuario tiene una sesion web activa.')),
                ('ultima_conexion', models.DateTimeField(blank=True, null=True)),
                ('ultima_salida', models.DateTimeField(blank=True, null=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='estado_sesion_cuenta', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Estado de sesion de usuario',
                'verbose_name_plural': 'Estados de sesion de usuarios',
                'db_table': 'usuarios_estado_sesion',
                'indexes': [models.Index(fields=['sesion_activa'], name='usuarios_es_sesion__b0cbd8_idx'), models.Index(fields=['fecha_actualizacion'], name='usuarios_es_fecha_a_a054e9_idx')],
            },
        ),
    ]
