# Generated by Django 5.2.14 on 2026-05-26 06:05

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MensajeJuegoResponsable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=120)),
                ('mensaje', models.TextField()),
                ('activo', models.BooleanField(default=True)),
                ('ubicacion', models.CharField(default='pantallas_apuesta', help_text='Ejemplo: pantallas_apuesta, dashboard, footer.', max_length=80)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Mensaje de juego responsable',
                'verbose_name_plural': 'Mensajes de juego responsable',
                'db_table': 'juego_responsable_mensaje',
                'ordering': ['ubicacion', 'titulo'],
                'indexes': [models.Index(fields=['activo'], name='juego_respo_activo_c2115e_idx'), models.Index(fields=['ubicacion'], name='juego_respo_ubicaci_37f65d_idx')],
            },
        ),
        migrations.CreateModel(
            name='Autoexclusion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('finalizada', 'Finalizada')], default='activa', max_length=20)),
                ('duracion', models.CharField(choices=[('7_dias', '7 días'), ('30_dias', '30 días'), ('90_dias', '90 días'), ('indefinida', 'Indefinida')], max_length=20)),
                ('fecha_inicio', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_fin', models.DateTimeField(blank=True, help_text='Vacío cuando la autoexclusión es indefinida.', null=True)),
                ('motivo', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('creada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='autoexclusiones_creadas', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autoexclusiones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Autoexclusión',
                'verbose_name_plural': 'Autoexclusiones',
                'db_table': 'juego_responsable_autoexclusion',
                'ordering': ['-fecha_inicio'],
                'indexes': [models.Index(fields=['usuario'], name='juego_respo_usuario_109176_idx'), models.Index(fields=['estado'], name='juego_respo_estado_67f336_idx'), models.Index(fields=['duracion'], name='juego_respo_duracio_ed3ed9_idx'), models.Index(fields=['fecha_inicio'], name='juego_respo_fecha_i_fd921a_idx'), models.Index(fields=['fecha_fin'], name='juego_respo_fecha_f_43d0e0_idx')],
            },
        ),
        migrations.CreateModel(
            name='LimiteDeposito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limite_diario', models.DecimalField(decimal_places=4, default=0, help_text='Límite diario de recarga simulada de fichas.', max_digits=18)),
                ('limite_semanal', models.DecimalField(decimal_places=4, default=0, help_text='Límite semanal de recarga simulada de fichas.', max_digits=18)),
                ('limite_mensual', models.DecimalField(decimal_places=4, default=0, help_text='Límite mensual de recarga simulada de fichas.', max_digits=18)),
                ('cambio_pendiente_diario', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('cambio_pendiente_semanal', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('cambio_pendiente_mensual', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('aplicar_cambio_en', models.DateTimeField(blank=True, help_text='Fecha en la que se aplica el aumento de límite.', null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='limite_deposito', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Límite de depósito',
                'verbose_name_plural': 'Límites de depósito',
                'db_table': 'juego_responsable_limite_deposito',
                'indexes': [models.Index(fields=['usuario'], name='juego_respo_usuario_9cd3f0_idx'), models.Index(fields=['aplicar_cambio_en'], name='juego_respo_aplicar_46a6be_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('limite_diario__gte', 0)), name='limite_diario_no_negativo'), models.CheckConstraint(condition=models.Q(('limite_semanal__gte', 0)), name='limite_semanal_no_negativo'), models.CheckConstraint(condition=models.Q(('limite_mensual__gte', 0)), name='limite_mensual_no_negativo')],
            },
        ),
    ]
