# Generated by Django 5.2.14 on 2026-05-24 06:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cuotas', '0001_initial'),
        ('mercados', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('simple', 'Simple'), ('combinada', 'Combinada')], default='simple', max_length=20)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('accepted', 'Aceptada'), ('won', 'Ganada'), ('lost', 'Perdida'), ('cancelled', 'Cancelada'), ('cashed_out', 'Cash-out'), ('void', 'Anulada')], default='borrador', max_length=20)),
                ('stake', models.DecimalField(decimal_places=4, help_text='Monto apostado en fichas virtuales.', max_digits=18)),
                ('odds_total', models.DecimalField(decimal_places=4, help_text='Cuota total de la apuesta.', max_digits=18)),
                ('payout_potencial', models.DecimalField(decimal_places=4, help_text='Pago potencial si la apuesta gana.', max_digits=18)),
                ('payout_final', models.DecimalField(blank=True, decimal_places=4, help_text='Pago final después de liquidar.', max_digits=18, null=True)),
                ('idempotency_key', models.CharField(blank=True, help_text='Clave para evitar apuestas duplicadas.', max_length=120, null=True, unique=True)),
                ('ip_origen', models.GenericIPAddressField(blank=True, null=True)),
                ('aceptada_en', models.DateTimeField(blank=True, null=True)),
                ('liquidada_en', models.DateTimeField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='apuestas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Apuesta',
                'verbose_name_plural': 'Apuestas',
                'db_table': 'apuestas_bet',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='BetSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('odd_valor_tomado', models.DecimalField(decimal_places=4, help_text='Cuota capturada al momento de aceptar la apuesta.', max_digits=18)),
                ('resultado', models.CharField(choices=[('pendiente', 'Pendiente'), ('ganada', 'Ganada'), ('perdida', 'Perdida'), ('anulada', 'Anulada')], default='pendiente', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('bet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selecciones', to='apuestas_core.bet')),
                ('odd', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='apuestas_selecciones', to='cuotas.odd')),
                ('seleccion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='apuestas_selecciones', to='mercados.seleccionmercado')),
            ],
            options={
                'verbose_name': 'Selección de apuesta',
                'verbose_name_plural': 'Selecciones de apuesta',
                'db_table': 'apuestas_bet_selection',
                'ordering': ['bet', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='bet',
            index=models.Index(fields=['usuario'], name='apuestas_be_usuario_4b92fb_idx'),
        ),
        migrations.AddIndex(
            model_name='bet',
            index=models.Index(fields=['estado'], name='apuestas_be_estado_7f6bf2_idx'),
        ),
        migrations.AddIndex(
            model_name='bet',
            index=models.Index(fields=['tipo'], name='apuestas_be_tipo_c6e735_idx'),
        ),
        migrations.AddIndex(
            model_name='bet',
            index=models.Index(fields=['idempotency_key'], name='apuestas_be_idempot_85b092_idx'),
        ),
        migrations.AddIndex(
            model_name='bet',
            index=models.Index(fields=['fecha_creacion'], name='apuestas_be_fecha_c_32718d_idx'),
        ),
        migrations.AddConstraint(
            model_name='bet',
            constraint=models.CheckConstraint(condition=models.Q(('stake__gt', 0)), name='bet_stake_mayor_que_cero'),
        ),
        migrations.AddConstraint(
            model_name='bet',
            constraint=models.CheckConstraint(condition=models.Q(('odds_total__gt', 1)), name='bet_odds_total_mayor_que_uno'),
        ),
        migrations.AddConstraint(
            model_name='bet',
            constraint=models.CheckConstraint(condition=models.Q(('payout_potencial__gte', 0)), name='bet_payout_potencial_no_negativo'),
        ),
        migrations.AddIndex(
            model_name='betselection',
            index=models.Index(fields=['bet'], name='apuestas_be_bet_id_eb93f4_idx'),
        ),
        migrations.AddIndex(
            model_name='betselection',
            index=models.Index(fields=['seleccion'], name='apuestas_be_selecci_b011dc_idx'),
        ),
        migrations.AddIndex(
            model_name='betselection',
            index=models.Index(fields=['odd'], name='apuestas_be_odd_id_a8c49a_idx'),
        ),
        migrations.AddIndex(
            model_name='betselection',
            index=models.Index(fields=['resultado'], name='apuestas_be_resulta_326f88_idx'),
        ),
        migrations.AddConstraint(
            model_name='betselection',
            constraint=models.CheckConstraint(condition=models.Q(('odd_valor_tomado__gt', 1)), name='bet_selection_odd_valor_mayor_que_uno'),
        ),
    ]
