# Generated by Django 5.2.14 on 2026-05-24 05:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('wallet_usuario', 'Wallet de usuario'), ('casa', 'Casa'), ('apuestas_pendientes', 'Apuestas pendientes'), ('bonos', 'Bonos')], max_length=40)),
                ('nombre', models.CharField(max_length=120)),
                ('activa', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cuentas_ledger', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cuenta contable',
                'verbose_name_plural': 'Cuentas contables',
                'db_table': 'billetera_account',
                'ordering': ['tipo', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='LedgerTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('recarga', 'Recarga simulada'), ('retiro', 'Retiro simulado'), ('transferencia', 'Transferencia interna'), ('bloqueo_apuesta', 'Bloqueo por apuesta'), ('liquidacion_apuesta', 'Liquidación de apuesta'), ('cashout', 'Cash-out'), ('bono', 'Bono promocional')], max_length=40)),
                ('referencia', models.CharField(blank=True, help_text='Referencia externa o interna de la operación.', max_length=120, null=True)),
                ('idempotency_key', models.CharField(blank=True, help_text='Clave para evitar operaciones duplicadas.', max_length=120, null=True, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transacciones_ledger_creadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transacción ledger',
                'verbose_name_plural': 'Transacciones ledger',
                'db_table': 'billetera_ledger_transaction',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=4, help_text='Monto en fichas virtuales. No usar float.', max_digits=18)),
                ('direction', models.CharField(choices=[('DEBIT', 'Débito'), ('CREDIT', 'Crédito')], max_length=10)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='billetera.account')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='billetera.ledgertransaction')),
            ],
            options={
                'verbose_name': 'Entrada ledger',
                'verbose_name_plural': 'Entradas ledger',
                'db_table': 'billetera_ledger_entry',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['tipo'], name='billetera_a_tipo_5aba47_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['usuario'], name='billetera_a_usuario_b3c91d_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['activa'], name='billetera_a_activa_39c79e_idx'),
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.UniqueConstraint(fields=('usuario', 'tipo'), name='unique_account_tipo_por_usuario'),
        ),
        migrations.AddIndex(
            model_name='ledgertransaction',
            index=models.Index(fields=['tipo'], name='billetera_l_tipo_38b784_idx'),
        ),
        migrations.AddIndex(
            model_name='ledgertransaction',
            index=models.Index(fields=['referencia'], name='billetera_l_referen_778c10_idx'),
        ),
        migrations.AddIndex(
            model_name='ledgertransaction',
            index=models.Index(fields=['idempotency_key'], name='billetera_l_idempot_33108f_idx'),
        ),
        migrations.AddIndex(
            model_name='ledgertransaction',
            index=models.Index(fields=['fecha_creacion'], name='billetera_l_fecha_c_b50994_idx'),
        ),
        migrations.AddIndex(
            model_name='ledgerentry',
            index=models.Index(fields=['transaction'], name='billetera_l_transac_6cbbd6_idx'),
        ),
        migrations.AddIndex(
            model_name='ledgerentry',
            index=models.Index(fields=['account'], name='billetera_l_account_10d704_idx'),
        ),
        migrations.AddIndex(
            model_name='ledgerentry',
            index=models.Index(fields=['direction'], name='billetera_l_directi_c1a103_idx'),
        ),
        migrations.AddIndex(
            model_name='ledgerentry',
            index=models.Index(fields=['fecha_creacion'], name='billetera_l_fecha_c_e0f649_idx'),
        ),
        migrations.AddConstraint(
            model_name='ledgerentry',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='ledger_entry_amount_gt_zero'),
        ),
    ]
